SOP = ipc.get("FSLC_SOP")
pilot = ipc.get("FSLC_PM")
after_start = ipc.get("FSLC_after_start")
lineup = ipc.get("FSLC_lineup")
after_takeoff = ipc.get("FSLC_after_takeoff")
landing = ipc.get("FSLC_landing")
packs_on_takeoff = ipc.get("FSLC_packs_on_takeoff")
pack2_off_after_landing = ipc.get("FSLC_pack2_off_after_landing")
FSL = require("FSLC_lib")
require("FSLabs Copilot\\SOP\\" .. SOP)